export const LIST_TABLE_TOKENS = {
    header: "bg-secondary/20",
    headerRow: "hover:bg-transparent border-none",
    headBase:
        "text-[10px] font-bold text-muted-foreground uppercase tracking-widest py-4",
    body: "divide-y divide-border/10",
    row: "group border-none hover:bg-secondary/30 transition-all h-12",
    rowClickable: "cursor-pointer",
    cellText: "text-xs",
    monoMuted: "text-xs font-mono text-muted-foreground",
    idCell: "text-center",
    idText: "text-xs font-mono font-bold tracking-wide text-foreground/45",
    badgeCell: "text-center",
    badgeWrap: "flex justify-center",
    roleCell: "text-center text-xs font-semibold text-foreground/75",
    colId: "w-[140px]",
    colAmount: "w-[140px]",
    colStatus: "w-[130px]",
    colDate: "w-[160px]",
    colActions: "w-[120px]",
};
