export const LIST_TABLE_TOKENS = {
    header: "bg-primary/20",
    headerRow: "hover:bg-transparent border-b border-border/60",
    headBase:
        "text-[11px] font-semibold text-primary/95 uppercase tracking-[0.06em] py-4",
    body: "[&_td]:text-[13px] [&_td]:font-medium [&_td]:text-foreground/85",
    row: "group h-12 border-b border-border/60 hover:bg-primary/6 transition-colors",
    rowClickable: "cursor-pointer",
    cellText: "text-xs",
    monoMuted: "text-[13px] font-mono text-foreground/70",
    idCell: "text-center",
    idText: "text-[13px] font-mono font-semibold tracking-[0.02em] text-foreground/65",
    dateCell: "text-center text-muted-foreground font-semibold text-[13px]",
    badgeCell: "text-center",
    badgeWrap: "flex justify-center",
    roleCell: "text-center text-[13px] font-medium text-foreground/75",
    amountCell: "text-right pr-4",
    amountWrap: "flex items-center justify-between gap-2",
    amountSymbol: "text-[10px] font-bold text-muted-foreground",
    amountValue: "text-base font-bold tracking-tight text-foreground",
    colId: "w-[140px]",
    colAmount: "w-[140px]",
    colStatus: "w-[130px]",
    colDate: "w-[160px]",
    colActions: "w-[120px]",
};
