export const LIST_TABLE_TOKENS = {
    header: "bg-primary/20",
    headerRow: "hover:bg-transparent border-none",
    headBase:
        "text-[11px] font-semibold text-primary/95 uppercase tracking-[0.06em] py-4",
    body: "divide-y divide-border/10 [&_td]:text-[13px] [&_td]:font-medium [&_td]:text-foreground/85",
    row: "group border-none hover:bg-primary/6 transition-colors h-12",
    rowClickable: "cursor-pointer",
    cellText: "text-xs",
    monoMuted: "text-[13px] font-mono text-foreground/70",
    idCell: "text-center",
    idText: "text-[13px] font-mono font-semibold tracking-[0.02em] text-foreground/65",
    badgeCell: "text-center",
    badgeWrap: "flex justify-center",
    roleCell: "text-center text-[13px] font-medium text-foreground/75",
    colId: "w-[140px]",
    colAmount: "w-[140px]",
    colStatus: "w-[130px]",
    colDate: "w-[160px]",
    colActions: "w-[120px]",
};
